name: example-environment

dependencies:
  - numpy
  - matplotlib
  - astropy
  - emcee
  - dill
  - pip:
    - lmfit
    - corner
    - batman-package
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
    - git+https://github.com/dfm/python-bls.git
